/**
 * Sprint 4 Step 58 — AI Explanation Quality + Cost Optimization.
 *
 * ## Cost calculation architecture
 *
 * The Anthropic Messages API returns real token-usage metadata on every
 * response (`response.usage.input_tokens` / `output_tokens`) — that part is
 * provider-supplied fact, already captured on `IAiTokenUsage`
 * (`models/AIHistory.model.ts`). It does **not** return a USD cost field, so
 * "cost tracking where provider metadata permits" means: take the metadata
 * the provider gives us (token counts) and price it ourselves against a
 * manually-maintained rate table — this file.
 *
 * Rates are USD per **million** tokens, matching how Anthropic publishes
 * pricing, keyed by the literal `model` string stored on each `AIHistory`/
 * `AIExplanation` row. Update this table if Anthropic repriced Claude Haiku
 * 4.5, or when `config/anthropic.ts#AI_MODEL` is ever changed to a different
 * model — a model missing from this table is a deliberate "unknown cost"
 * signal (see `utils/aiCost.ts`), not a bug to silently zero out.
 *
 * Cost is computed **once, at generation time** (`utils/aiCost.ts#estimateCostUsd`,
 * called from `services/ai/questionExplanation.service.ts` right after a real
 * provider call returns usage) and stored on that `AIHistory` row as
 * `estimatedCostUsd` — never recomputed later from the live table. This
 * matters because pricing can change: if cost were derived at *read* time
 * (e.g. in the admin usage aggregation), a rate change would silently
 * rewrite the reported cost of last month's already-billed requests. Storing
 * it at write time keeps historical admin stats accurate to what the
 * generation actually cost under the pricing in effect that day.
 *
 * A cache hit (`source: 'cached'`) never calls the provider, so its
 * marginal cost is always exactly 0 — recorded explicitly as `0`, not left
 * undefined, so admin aggregation's `$sum` doesn't need a null-coalesce and
 * "0 requests cost tracked" is distinguishable from "requests cost $0".
 */

export interface AiModelRate {
  /** USD per 1,000,000 input tokens. */
  inputPerMillionUsd: number
  /** USD per 1,000,000 output tokens. */
  outputPerMillionUsd: number
}

/**
 * Keyed by the exact `model` string `config/anthropic.ts#AI_MODEL` sends to
 * the API — currently only `claude-haiku-4-5` is ever generated by this
 * app, but the table is keyed by model (not hardcoded) so a future model
 * change doesn't require touching the cost-calculation logic itself.
 */
export const AI_MODEL_RATES: Record<string, AiModelRate> = {
  'claude-haiku-4-5': { inputPerMillionUsd: 1.0, outputPerMillionUsd: 5.0 },
}
